//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eClaim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpenseDetail
    {
        public int DetailID { get; set; }
        public int ExpenseID { get; set; }
        public System.DateTime Date { get; set; }
        public int CostCenter { get; set; }
        public int GLCode { get; set; }
        public string Description { get; set; }
        public string Currency { get; set; }
        public Nullable<decimal> ExhangeRate { get; set; }
        public Nullable<decimal> Gst { get; set; }
        public Nullable<decimal> ClaimCurrAmount { get; set; }
        public decimal ClaimAmount { get; set; }
        public byte Status { get; set; }
    
        public virtual ExpenseMaster ExpenseMaster { get; set; }
    }
}
